use_frameworks!
platform :ios, '9.0'

target 'LHVideoDetailController_Example' do
  pod 'LHVideoDetailController', :path => '../'

  target 'LHVideoDetailController_Tests' do
    inherit! :search_paths

    
  end
end
